src/Controllers/MenuController.php, src/Controllers/PermissionController.php
菜单模型树和权限模型树显示时出现两个编辑按钮，一个是跳转编辑，一个是弹窗编辑，看上去不是很舒服。
因为弹窗编辑比较方便，所以去掉了跳转编辑。
=> 修复出现两个编辑按钮的问题

src/Grid/Column.php
很多业务中需要这个 `✓` 和 `✗` 来展示用户状态，业务状态。
=>  Display column as boolean , `✓` for true, and `✗` for false.

src/Show/Field.php
在詳情頁處理json字段時，如果跟dot一起用樣式會跑到default
```php
// application是個json字段 {"access": "no"}
$show->field('application.access', 'json')
->using([
'no' => '無法授權',
'yes' => '批准',
])
->dot([
'no' => 'danger',
'yes' => 'warning',
]);
```
=> update for json in show

src/Grid/Displayers/Editable.php
修复 Grid Column Editable 行内编辑字段值为空时不出现保存按钮
=> 修复 Grid Column Editable 行内编辑字段值为空时不出现保存按钮

resources/views/form/select.blade.php, src/Form/Field/Editor.php
1. 修复 TinyMCE 插入 视频资源，提交时，会将占位图代码一并保存。通过使用TinyMCE 的 `getContent()` 函数，获取最终提交值，可得到正确的 HTML代码。
2. 修复select2 分组选项时，一定会带默认值的问题。 应该缺省为空
=> Fix select2 和 TinyMCE 的一些问题

src/Form/Field/Editor.php
=> :bug: fix TinyMCE 插入视频，保存时，会将TinyMCE占位图代码保存下来

src/Repositories/EloquentRepository.php
当两个 Model 的关联关系为 `hasMany` ，但是表单没有通过 `$form->hasMany` 组件提交时，保存数据时会出现报错 “Undefined index: _remove_”。
我的模型定义为：
```php
class Article extends Model
{
public function pictures()
{
return $this->hasMay(Picture::class);
}
}
class Picture  extends Model
{
public function article()
{
return $this->belongsTo(Article::class);
}
}
```
表单代码为：
```php
class ArticleController extends AdminController
{
public function form()
{
return Form::make(new Article(['pictures']), function(Form $form) {
$form->saving(function (Form $form) {
$form->input('pictures, [
['path' => 'xxx'], ['path' => 'xxx'],
]);
});
// 其他表单代码
});
}
}
这个 PR 中将直接访问数组下标的代码，修改成了 `Arr::get()` ，这样一来可以使用其中的 `array_key_exists` 方法检查数组是否真的有这个索引，从而不再导致以上报错。
=> 修复模型中存在 hasMany 关联属性时保存数据会报 “Undefined index: _remove_” 错误的问题

src/Grid/Filter.php
修复 数据表格搜索时 Dcat\Admin\Grid\Events\Event::__construct() 第一个参数 应为 Dcat\Admin\Grid 实际为Dcat\Admin\Grid\Filter 的BUG
=> 修复 数据表格搜索BUG

src/Grid/Filter/Presenter/MultipleSelectTable.php
使用 MultipleSelectTable 时，报错 Array to string conversion，发现为 js 拼接时传入的数据类型问题。
=> 解决 MultipleSelectTable 中 js 中接收数据类型问题

src/Form/Field.php, src/Grid/Column.php, src/Grid/Filter/AbstractFilter.php, src/Show/Field.php
If there is a programmer provided label we should pass it through. If not we don't need to replace dots, because admin_trans_field uses admin_trans that already removes dots if there are no translations available (it uses text after the last dot).
=> Unify formatLabel methods and fix error with dots replacing in translation

src/Grid/Displayers/DropdownActions.php
You have changed the code to use the "appends" variable from the parent "Actions" class instead of the "custom" variable, so we don't need it anymore.
=> Remove unused variable "custom" from DropdownActions class

resources/lang/en/admin.php, resources/lang/zh_CN/admin.php, resources/lang/zh_TW/admin.php, resources/views/helpers/scaffold.blade.php
这个PR可以解决一部分重复劳动工作，添加字段的时候不用再一个一个的复制翻译输入框的内容粘贴到注释输入框里了。
现在你可以在翻译里先写好内容，然后点一下按钮，注释里的内容就自动填充好了，当然也可以反着来，或者注释和翻译各写一部分，然后点这个按钮就好了。
=> 代码生成器添加注释与翻译互填功能

src/Models/Permission.php
It should be possible to easily create tree permissions in migrations for example using the Permission::create method - now it's not.
"parent_id" is already in the Menu model $fillable array, so let's make it here too.
=> Allow to set parent_id in permission model using create method

resources/views/filter/multipleselect.blade.php
当使用联动时，父母级请求到联动数据后，将原选项清空并重新插入请求到的选项，在这一步中会丢失balde渲染的数据，而在resources/views/scripts/select.blade.php 中，已有通过属性data-value来二次赋值的逻辑，故利用之。
可能造成的影响：
1. 当再次回到父级的初始选项时，保存的数据不会被清空
2. 其它父级联动出的数据可能会产生脏数据
可选解决方案[TODO]：
在 resources/views/filter/multipleselect.blade.php 中增加属性data-init-parent作为初始父级的当前选项值，并在
在 resources/views/scripts/select.blade.php 中判断 this.value 的值是否与了级属性data-init-parent相等来决定是否加载data-value。
=> 解决 联动加载后，初始值丢失的问题

src/Grid/Displayers/Actions.php
=> 修改错误的label使用

resources/views/form/file.blade.php
Without this change the `"</i>"` is ignored, so "Browse" text is in the "i" tag and it is using feather font.
=> Fix escaping of the upload button label

src/Traits/HasPermissions.php
Rename into this `boot{TraitName}()` style, can avoid `HasPermissions::boot()`'override by `config('admin.auth.providers.admin.model')::boot()`.
@see https://medium.com/swlh/laravel-booting-and-initializing-models-with-traits-2f77059b1915
=> rename `boot()` method into `boot{TraitName}()`

src/Application.php, src/Http/Controllers/AuthController.php
fixed: #398 
多后台登录:
admin1
admin2
如果先打开了 (同时打开多个后台登录页面)
admin1 跳转去登录页面 session.url.intended = admin1
然后打开
admin2 跳转去登录页面 session.url.intended = admin2
这时候回到 admin1 登录成功, 从 session 获取到上一个页面是 admin2
然后跳转到 admin2, 结果又跳转去 admin2 的登录页面(应该跳去 admin1 后台首页)
=> Fix: 多应用后台登录后跳转

src/Form/Field.php, src/Form/Field/Checkbox.php, src/Form/Field/Radio.php, src/Form/Field/Select.php, src/Form/Field/Text.php, src/Widgets/Radio.php
- input
- select
- checkbox
- radio
- `input`、`select`组件中新增了相应的类名；
- `checkbox`、`radio`组件中修复了`$size`变量未生效的问题;
- `src/Widgets/Radio.php`中的`small()`方法和`large()`方法放到了`src/Form/Field.php`中，部分子类如`src/Form/Field/SwitchField.php`可以重写这两个方法；
- 目前`input`和`select`组件即使指定了大小也不生效，需要通过`Admin::css()`添加CSS代码覆盖原有样式。
=> 修复常用组件大小样式未生效的问题

resources/assets/dcat/extra/upload.scss, resources/assets/dcat/plugins/webuploader/webuploader.css, resources/dist/dcat/plugins/webuploader/webuploader.css
优化图片在 web-loader Form 组件中的展示效果。
目前图片预览存在超过预设宽高的图片拉伸变形的情况，该 pull request 通过在图片标签添加 object-fit = cover 的属性做到图片的覆盖效果，保证图片不变形。
=> feat: improve the display effect of web-uploader images

src/Layout/Menu.php
=> 在拓展菜单时使用多语言翻译出现类不存在的问题

src/Grid/Filter/Presenter/SelectTable.php
如下调用方式导致输入框无内容或者错误的内容.
$grid->filter(function (Grid\Filter $filter) {
$filter->in('user_id')
->multipleSelectTable(UserProfile::make(['user_id' => request('user_id')]))
->model(UserProfileModel::class, 'user_id', 'mobile')
;
});
sql查询语句是:
select * from user_profile where id = xxxx
正确的sql语句应该是
select * from user_profile where user_id = xxxx
=> fix select table model
